resources:
  - service.yaml
  - mutating-webhook-configuration.yaml
  - deployment.yaml

secretGenerator:
  - name: fluentd-sidecar-injector-certs
    files:
      - cert.pem=certs/webhook.crt
      - key.pem=certs/webhookCA.key
    type: Opaque
