apiVersion: v1
kind: Service
metadata:
  name: fluentd-sidecar-injector-webhook
  labels:
    app: fluentd-sidecar-injector-webhook
spec:
  ports:
  - port: 443
    targetPort: 8080
  selector:
    app: fluentd-sidecar-injector
