apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    app: nginx-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      annotations:
        h3poteto.dev.fluentd-sidecar-injection: "enabled"
      labels:
        app: nginx-test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
