apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    app: nginx-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      annotations:
        fluentd-sidecar-injector.h3poteto.dev/injection: "enabled"
        fluentd-sidecar-injector.h3poteto.dev/aggregator-host: "127.0.0.1"
        fluentd-sidecar-injector.h3poteto.dev/application-log-dir: "/var/log/nginx"
        fluentd-sidecar-injector.h3poteto.dev/time-key: "time"
        fluentd-sidecar-injector.h3poteto.dev/tag-prefix: "test"
      labels:
        app: nginx-test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
